//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMD_Form.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ellistrtest.com/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GenerateHashResult from namespace http://www.ellistrtest.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ellistrtest.com/GenerateHash", ReplyAction="*")]
        GMD_Form.ServiceReference1.GenerateHashResponse GenerateHash(GMD_Form.ServiceReference1.GenerateHashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ellistrtest.com/GenerateHash", ReplyAction="*")]
        System.Threading.Tasks.Task<GMD_Form.ServiceReference1.GenerateHashResponse> GenerateHashAsync(GMD_Form.ServiceReference1.GenerateHashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ellistrtest.com/RegisterUser", ReplyAction="*")]
        GMD_Form.ServiceReference1.RegisterUserResponse RegisterUser(GMD_Form.ServiceReference1.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ellistrtest.com/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<GMD_Form.ServiceReference1.RegisterUserResponse> RegisterUserAsync(GMD_Form.ServiceReference1.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ellistrtest.com/updateLoyalty", ReplyAction="*")]
        void updateLoyalty();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ellistrtest.com/updateLoyalty", ReplyAction="*")]
        System.Threading.Tasks.Task updateLoyaltyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ellistrtest.com/getBalance", ReplyAction="*")]
        long getBalance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ellistrtest.com/getBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<long> getBalanceAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateHashRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateHash", Namespace="http://www.ellistrtest.com/", Order=0)]
        public GMD_Form.ServiceReference1.GenerateHashRequestBody Body;
        
        public GenerateHashRequest() {
        }
        
        public GenerateHashRequest(GMD_Form.ServiceReference1.GenerateHashRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GenerateHashRequestBody {
        
        public GenerateHashRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateHashResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateHashResponse", Namespace="http://www.ellistrtest.com/", Order=0)]
        public GMD_Form.ServiceReference1.GenerateHashResponseBody Body;
        
        public GenerateHashResponse() {
        }
        
        public GenerateHashResponse(GMD_Form.ServiceReference1.GenerateHashResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ellistrtest.com/")]
    public partial class GenerateHashResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateHashResult;
        
        public GenerateHashResponseBody() {
        }
        
        public GenerateHashResponseBody(string GenerateHashResult) {
            this.GenerateHashResult = GenerateHashResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://www.ellistrtest.com/", Order=0)]
        public GMD_Form.ServiceReference1.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(GMD_Form.ServiceReference1.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ellistrtest.com/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long socialSecurityNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long mobileNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int PIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long userID;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(string firstName, string lastName, long socialSecurityNumber, long mobileNumber, int PIN, long userID) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.socialSecurityNumber = socialSecurityNumber;
            this.mobileNumber = mobileNumber;
            this.PIN = PIN;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://www.ellistrtest.com/", Order=0)]
        public GMD_Form.ServiceReference1.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(GMD_Form.ServiceReference1.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ellistrtest.com/")]
    public partial class RegisterUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long RegisterUserResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long userID;
        
        public RegisterUserResponseBody() {
        }
        
        public RegisterUserResponseBody(long RegisterUserResult, long userID) {
            this.RegisterUserResult = RegisterUserResult;
            this.userID = userID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : GMD_Form.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<GMD_Form.ServiceReference1.WebService1Soap>, GMD_Form.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GMD_Form.ServiceReference1.GenerateHashResponse GMD_Form.ServiceReference1.WebService1Soap.GenerateHash(GMD_Form.ServiceReference1.GenerateHashRequest request) {
            return base.Channel.GenerateHash(request);
        }
        
        public string GenerateHash() {
            GMD_Form.ServiceReference1.GenerateHashRequest inValue = new GMD_Form.ServiceReference1.GenerateHashRequest();
            inValue.Body = new GMD_Form.ServiceReference1.GenerateHashRequestBody();
            GMD_Form.ServiceReference1.GenerateHashResponse retVal = ((GMD_Form.ServiceReference1.WebService1Soap)(this)).GenerateHash(inValue);
            return retVal.Body.GenerateHashResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GMD_Form.ServiceReference1.GenerateHashResponse> GMD_Form.ServiceReference1.WebService1Soap.GenerateHashAsync(GMD_Form.ServiceReference1.GenerateHashRequest request) {
            return base.Channel.GenerateHashAsync(request);
        }
        
        public System.Threading.Tasks.Task<GMD_Form.ServiceReference1.GenerateHashResponse> GenerateHashAsync() {
            GMD_Form.ServiceReference1.GenerateHashRequest inValue = new GMD_Form.ServiceReference1.GenerateHashRequest();
            inValue.Body = new GMD_Form.ServiceReference1.GenerateHashRequestBody();
            return ((GMD_Form.ServiceReference1.WebService1Soap)(this)).GenerateHashAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GMD_Form.ServiceReference1.RegisterUserResponse GMD_Form.ServiceReference1.WebService1Soap.RegisterUser(GMD_Form.ServiceReference1.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public long RegisterUser(string firstName, string lastName, long socialSecurityNumber, long mobileNumber, int PIN, ref long userID) {
            GMD_Form.ServiceReference1.RegisterUserRequest inValue = new GMD_Form.ServiceReference1.RegisterUserRequest();
            inValue.Body = new GMD_Form.ServiceReference1.RegisterUserRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.socialSecurityNumber = socialSecurityNumber;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.PIN = PIN;
            inValue.Body.userID = userID;
            GMD_Form.ServiceReference1.RegisterUserResponse retVal = ((GMD_Form.ServiceReference1.WebService1Soap)(this)).RegisterUser(inValue);
            userID = retVal.Body.userID;
            return retVal.Body.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GMD_Form.ServiceReference1.RegisterUserResponse> GMD_Form.ServiceReference1.WebService1Soap.RegisterUserAsync(GMD_Form.ServiceReference1.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<GMD_Form.ServiceReference1.RegisterUserResponse> RegisterUserAsync(string firstName, string lastName, long socialSecurityNumber, long mobileNumber, int PIN, long userID) {
            GMD_Form.ServiceReference1.RegisterUserRequest inValue = new GMD_Form.ServiceReference1.RegisterUserRequest();
            inValue.Body = new GMD_Form.ServiceReference1.RegisterUserRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.socialSecurityNumber = socialSecurityNumber;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.PIN = PIN;
            inValue.Body.userID = userID;
            return ((GMD_Form.ServiceReference1.WebService1Soap)(this)).RegisterUserAsync(inValue);
        }
        
        public void updateLoyalty() {
            base.Channel.updateLoyalty();
        }
        
        public System.Threading.Tasks.Task updateLoyaltyAsync() {
            return base.Channel.updateLoyaltyAsync();
        }
        
        public long getBalance() {
            return base.Channel.getBalance();
        }
        
        public System.Threading.Tasks.Task<long> getBalanceAsync() {
            return base.Channel.getBalanceAsync();
        }
    }
}
